#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.kaiwei.project.entity
#  typeEnumsPackage: com.hy.serverside.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type:  auto # #id_worker 废弃
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      # column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      table-underline: true
      #逻辑删除配置
      logic-delete-field: deleted  #全局逻辑删除字段值 3.3.0开始支持
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    #刷新mapper 调试神器
    # refresh: true (被废弃)
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
##logging
#logging:
#  level: warn